### ISSUE TITLE
Running example code issue

### ISSUE THREAD

**Issue by kimbring2** [oscarknagg/wurm#4]
Hello, Oscar

Thank you for showing nice code.

I tried to run that code, but had some issue.

At main.py, 'a2c = A2C(model, gamma=args.gamma)' give a error message like a
' **TypeError: __init__() got multiple values for argument 'gamma'** '.

I find that A2C class do not receive a model argument. Thus, I modify that like as 'a2c = A2C(gamma=args.gamma)'.

At the, I get another error message like ' **RuntimeError: The size of tensor a (512) must match the size of tensor b (20) at non-singleton dimension 1** '.

It runs well when I set a num-envs argument same as a a update-steps argument'

Finally, I can run code after commenting out a 'logger.write(logs)' line because of some error.

However, even after turning the code like this, it seems that the length of the snake continues to 3 even after 30 minutes.

If you have any modified code, please let me know.

Thank you.
From Dohyeong

**Comment by Andrew-Pynch** [comment]
Same issue here... Any thoughts?

**Comment by kimbring2** [comment]
@Andrew-Pynch If you need to get some code about Relational Deep RL, try to use a code at https://github.com/gyh75520/Relational_DRL. It is work well. 

I will close the that issue.

**Comment by Andrew-Pynch** [comment]
Thank you!
